<?php
/*
 * default options if the options not set by theme options.
 */
$header=array(
	'head_type'=>0,
	'logo'=> get_bloginfo('template_directory').'/images/albizia.png',
	'bg'=> '',
	'image'=>'',
	'repeat'=>'no-repeat',
	'v_align'=>'top',
	'h_align'=>'center',
	'scope'=>0,
	'height'=>'',
	'color'=>'#ffffff',
	'hover_color'=>'#aaffff',
	'span_color'=>'#eeffff',
	'bgcolor'=>'transparent',
	'text_align'=>'center',
	'font_size'=>'3.5em',
	'span_font_size'=>'1.8em',
	);
$bg=array(
	'image'=> get_bloginfo('template_directory').'/images/albiziabg.jpg',
	'attachment'=>'scroll',
	'repeat'=>'no-repeat',
	'bgcolor'=>'',
	'v_align'=>'top',
	'h_align'=>'center',
	'resize'=>'100',
	);
$links=array(
	'rss'=>get_bloginfo('rss2_url'),
	'crss'=>get_bloginfo('comments_rss2_url'),
	'twitter'=>'itx_',
	'facebook'=>'AlbiziaTheme',
	);
$front=array(
	'type'=>'fe',
	'archive_type'=>'excerpt',
	'column'=>2,
	'featuredlim'=>70,
	'excerptlim'=>20,
	'featuredx'=>300,
	'featuredy'=>200,
	'fnotimg'=>'',
	'thumbx'=>150,
	'thumby'=>100,
	'notimg'=>'',
	'catch'=>1,
	'not'=>1,
	'fnotimg'=>'',
	'notimg'=>'',
	'excerpt_more'=>'...Read the Rest',
	'meta'=>array('commentcount'=>'commentcount','left'=>'date'),
	'post_meta'=>array('commentcount'=>1,'date'=>1,'author'=>'','categories'=>1,'tags'=>1,'author_info'=>''),
	);
$menu=array(
	'wp_menu'=>1,
	'top_home'=>'Home',
	'top_align'=>'right',
	'top_depth'=>0,
	'top_show'=>'page',
	'top_margin'=>180,
	'top_bg_color'=>'',
	'home'=>'Home',
	'align'=>'center',
	'depth'=>0,
	'cat_inc'=>array(),
	'cat_sortby'=>'name',
	'cat_order'=>'ASC',
	'page_inc'=>array(),
	'page_sortby'=>'post_title',
	'page_order'=>'ASC',
	'show'=>'cat'
	);
$layout=array(
	'column'=>3,
	'wrap'=>'1000',
	'wrapping'=>'flex',
	'sidebar1'=>'300',
	'sidebar2'=>'150',
	'sidebarunit'=>'px',
	'style'=>get_option(get_stylesheet().'_default_style'),
	'innertop'=>2,
	'innerbottom'=>2,
	'footer'=>4,
	);
$single=array(
	'post_meta'=>array('commentcount'=>1,'date'=>1,'author'=>'author_posts','categories'=>1,'tags'=>1,'author_info'=>''),
	'page_meta'=>array('commentcount'=>1,'author'=>'','author_info'=>''),
);
$css=array();
$misc=array(
	'favicon'=> get_bloginfo('template_directory').'/images/favicon.ico'
	);
?>